
import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  Search, Info, Beaker, Zap, Github, RotateCw, AlertCircle, Loader2,
  Database, BarChart3, FileText, Eye, Download, Sun, Moon, ChevronDown,
  Check, X, Bell, FlaskConical, Table2, Atom, GitBranch, Cpu, Dna,
  Plus, Trash2, ExternalLink
} from 'lucide-react';
import { AppStatus, MoleculeData } from './types';
import { PRESET_MOLECULES } from './constants';
import { fetchMoleculeData } from './services/geminiService';
import MoleculeCanvas from './components/MoleculeCanvas';

// ============================================================================
// TYPES
// ============================================================================

type TabId = 'viewer' | 'analysis' | 'notebooks' | 'database';
type ExportFormat = 'pdb' | 'xyz' | 'mol' | 'json';
type ToastType = 'success' | 'error' | 'info';

interface Toast {
  id: string;
  message: string;
  type: ToastType;
}

interface AnalysisModule {
  id: string;
  name: string;
  description: string;
  icon: React.ReactNode;
  color: string;
}

interface NotebookEntry {
  id: string;
  name: string;
  timestamp: number;
  moleculeName: string;
}

interface PubChemResult {
  cid: number;
  name: string;
  formula: string;
}

// ============================================================================
// CONSTANTS
// ============================================================================

const ANALYSIS_MODULES: AnalysisModule[] = [
  { id: 'bond-analysis', name: 'Bond Analysis', description: 'Analyze bond lengths and angles', icon: <GitBranch size={20} />, color: 'bg-blue-500' },
  { id: 'electron-density', name: 'Electron Density', description: 'Visualize electron distribution', icon: <Atom size={20} />, color: 'bg-purple-500' },
  { id: 'molecular-dynamics', name: 'Molecular Dynamics', description: 'Simulate molecular motion', icon: <Cpu size={20} />, color: 'bg-green-500' },
  { id: 'docking', name: 'Protein Docking', description: 'Predict protein-ligand binding', icon: <FlaskConical size={20} />, color: 'bg-orange-500' },
  { id: 'qsar', name: 'QSAR Analysis', description: 'Quantitative structure-activity relationships', icon: <BarChart3 size={20} />, color: 'bg-red-500' },
  { id: 'fragment', name: 'Fragment Analysis', description: 'Identify molecular fragments', icon: <Dna size={20} />, color: 'bg-teal-500' },
];

const EXPORT_FORMATS: { format: ExportFormat; label: string; ext: string }[] = [
  { format: 'pdb', label: 'PDB Format', ext: '.pdb' },
  { format: 'xyz', label: 'XYZ Format', ext: '.xyz' },
  { format: 'mol', label: 'MOL Format', ext: '.mol' },
  { format: 'json', label: 'JSON Format', ext: '.json' },
];

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

const generateId = () => Math.random().toString(36).substring(2, 9);

const exportMolecule = (data: MoleculeData, format: ExportFormat): string => {
  switch (format) {
    case 'xyz': {
      const coords = data.atoms.map(a => `${a.element} ${a.x.toFixed(6)} ${a.y.toFixed(6)} ${a.z.toFixed(6)}`).join('\n');
      return `${data.atoms.length}\n${data.name}\n${coords}`;
    }
    case 'json':
      return JSON.stringify(data, null, 2);
    case 'pdb': {
      const lines = ['HEADER    GENERATED BY MOLECULE STUDIO', `TITLE     ${data.name}`, `COMPND    ${data.name}`];
      data.atoms.forEach((atom, i) => {
        lines.push(`HETATM${String(i + 1).padStart(5)}  ${atom.element.padEnd(2)} MOL     1    ${atom.x.toFixed(3).padStart(8)}${atom.y.toFixed(3).padStart(8)}${atom.z.toFixed(3).padStart(8)}  1.00  0.00          ${atom.element.padStart(2)}`);
      });
      data.bonds.forEach(([a, b]) => {
        lines.push(`CONECT${String(a + 1).padStart(5)}${String(b + 1).padStart(5)}`);
      });
      lines.push('END');
      return lines.join('\n');
    }
    case 'mol': {
      const lines = [
        `${data.name}`.padEnd(30) + `${new Date().toISOString().slice(0, 10).replace(/-/g, '')}2D`,
        '  -ISIS-',
        '',
        `${String(data.atoms.length).padStart(3)}${String(data.bonds.length).padStart(3)}  0  0  0  0  0  0  0  1  0  0  0`,
      ];
      data.atoms.forEach(atom => {
        lines.push(`${atom.x.toFixed(4).padStart(10)}${atom.y.toFixed(4).padStart(10)}${atom.z.toFixed(4).padStart(10)} ${atom.element.padEnd(2)}  0  0  0  0  0  0  0  0  0  0  0  0`);
      });
      data.bonds.forEach(([a, b]) => {
        lines.push(`${String(a + 1).padStart(3)}${String(b + 1).padStart(3)}  1  0  0  0  0`);
      });
      return lines.join('\n');
    }
    default:
      return '';
  }
};

const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// ============================================================================
// COMPONENTS
// ============================================================================

const ToastNotification: React.FC<{ toast: Toast; onDismiss: (id: string) => void }> = ({ toast, onDismiss }) => {
  useEffect(() => {
    const timer = setTimeout(() => onDismiss(toast.id), 4000);
    return () => clearTimeout(timer);
  }, [toast.id, onDismiss]);

  return (
    <div className={`flex items-center gap-3 px-4 py-3 rounded-xl shadow-lg border animate-slide-in ${
      toast.type === 'success' ? 'bg-green-50 border-green-200 text-green-800' :
      toast.type === 'error' ? 'bg-red-50 border-red-200 text-red-800' :
      'bg-blue-50 border-blue-200 text-blue-800'
    }`}>
      {toast.type === 'success' && <Check size={18} className="text-green-600" />}
      {toast.type === 'error' && <X size={18} className="text-red-600" />}
      {toast.type === 'info' && <Bell size={18} className="text-blue-600" />}
      <span className="text-sm font-medium">{toast.message}</span>
      <button onClick={() => onDismiss(toast.id)} className="ml-2 opacity-60 hover:opacity-100">
        <X size={14} />
      </button>
    </div>
  );
};

const TabButton: React.FC<{ id: TabId; label: string; icon: React.ReactNode; active: boolean; onClick: () => void }> = ({
  id, label, icon, active, onClick
}) => (
  <button
    onClick={onClick}
    className={`flex items-center gap-2 px-4 py-2.5 rounded-xl font-medium text-sm transition-all ${
      active ? 'bg-stone-900 text-white' : 'text-stone-500 hover:text-stone-900 hover:bg-stone-100'
    }`}
  >
    {icon}
    <span className="hidden sm:inline">{label}</span>
  </button>
);

const ConnectionStatus: React.FC<{ connected: boolean }> = ({ connected }) => (
  <div className="flex items-center gap-2 px-3 py-1.5 bg-stone-100 rounded-lg">
    <div className={`w-2 h-2 rounded-full ${connected ? 'bg-green-500 animate-pulse' : 'bg-red-500'}`} />
    <span className="text-xs font-medium text-stone-600">{connected ? 'API Connected' : 'Disconnected'}</span>
  </div>
);

// ============================================================================
// SIDEBAR CONTENT COMPONENTS
// ============================================================================

const ViewerSidebar: React.FC<{ data: MoleculeData | null; status: AppStatus; error: string | null; onSearch: (q: string) => void }> = ({
  data, status, error, onSearch
}) => (
  <div className="space-y-6">
    {status === AppStatus.LOADING && (
      <div className="space-y-4 animate-pulse">
        <div className="h-8 bg-stone-200 rounded w-3/4" />
        <div className="h-4 bg-stone-100 rounded w-1/2" />
        <div className="h-32 bg-stone-100 rounded w-full" />
      </div>
    )}

    {data && status !== AppStatus.LOADING && (
      <>
        <section>
          <span className="px-2 py-1 bg-stone-900 text-white text-[10px] font-bold rounded uppercase tracking-wider">
            {data.category}
          </span>
          <h2 className="text-4xl font-bold text-stone-900 mt-2">{data.name}</h2>
          <p className="text-lg font-mono text-stone-500">{data.formula}</p>
        </section>

        <section className="bg-white/60 p-5 rounded-2xl border border-stone-100 shadow-sm">
          <h3 className="text-sm font-bold text-stone-400 uppercase tracking-widest mb-3 flex items-center gap-2">
            <Info size={14} /> Description
          </h3>
          <p className="text-sm text-stone-600 leading-relaxed">{data.description}</p>
        </section>

        <section className="bg-white/60 p-5 rounded-2xl border border-stone-100 shadow-sm">
          <h3 className="text-sm font-bold text-stone-400 uppercase tracking-widest mb-3 flex items-center gap-2">
            <Zap size={14} /> Composition
          </h3>
          <div className="flex flex-wrap gap-2">
            <div className="bg-stone-50 px-3 py-1.5 rounded-lg border border-stone-100 text-xs font-medium text-stone-600">
              <span className="font-bold text-stone-900">{data.atoms.length}</span> Atoms
            </div>
            <div className="bg-stone-50 px-3 py-1.5 rounded-lg border border-stone-100 text-xs font-medium text-stone-600">
              <span className="font-bold text-stone-900">{data.bonds.length}</span> Bonds
            </div>
          </div>
        </section>

        <section>
          <h3 className="text-sm font-bold text-stone-400 uppercase tracking-widest mb-4">Quick Presets</h3>
          <div className="grid grid-cols-2 gap-2">
            {PRESET_MOLECULES.map((mol) => (
              <button
                key={mol}
                onClick={() => onSearch(mol)}
                className="px-4 py-2 bg-white border border-stone-200 rounded-xl text-xs font-medium text-stone-600 hover:bg-stone-900 hover:text-white hover:border-stone-900 transition-all text-left truncate"
              >
                {mol}
              </button>
            ))}
          </div>
        </section>
      </>
    )}

    {status === AppStatus.ERROR && (
      <div className="p-4 bg-red-50 border border-red-100 rounded-2xl text-red-600 flex flex-col gap-2">
        <div className="flex items-center gap-2 font-bold">
          <AlertCircle size={18} /> Error
        </div>
        <p className="text-sm opacity-80">{error}</p>
      </div>
    )}
  </div>
);

const AnalysisSidebar: React.FC<{ onLaunch: (moduleId: string) => void }> = ({ onLaunch }) => (
  <div className="space-y-6">
    <section>
      <h2 className="text-2xl font-bold text-stone-900">Analysis Modules</h2>
      <p className="text-sm text-stone-500 mt-1">Select a module to analyze your molecule</p>
    </section>

    <div className="grid gap-3">
      {ANALYSIS_MODULES.map((mod) => (
        <button
          key={mod.id}
          onClick={() => onLaunch(mod.id)}
          className="group p-4 bg-white rounded-xl border border-stone-200 hover:border-stone-400 hover:shadow-md transition-all text-left"
        >
          <div className="flex items-start gap-3">
            <div className={`p-2 rounded-lg ${mod.color} text-white`}>
              {mod.icon}
            </div>
            <div className="flex-1 min-w-0">
              <h3 className="font-semibold text-stone-900 group-hover:text-stone-700">{mod.name}</h3>
              <p className="text-xs text-stone-500 mt-0.5">{mod.description}</p>
            </div>
          </div>
        </button>
      ))}
    </div>

    <section className="p-4 bg-amber-50 border border-amber-100 rounded-xl">
      <h3 className="text-sm font-bold text-amber-800 mb-2">Pro Tip</h3>
      <p className="text-xs text-amber-700">Load a molecule in the 3D Viewer first, then launch an analysis module to get detailed insights.</p>
    </section>
  </div>
);

const NotebooksSidebar: React.FC<{
  notebooks: NotebookEntry[];
  activeNotebook: string | null;
  onSelect: (id: string) => void;
  onCreate: () => void;
  onDelete: (id: string) => void;
}> = ({ notebooks, activeNotebook, onSelect, onCreate, onDelete }) => {
  const formatDate = (ts: number) => new Date(ts).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });

  return (
    <div className="space-y-6">
      <section className="flex items-center justify-between">
        <h2 className="text-2xl font-bold text-stone-900">Notebooks</h2>
        <button
          onClick={onCreate}
          className="flex items-center gap-2 px-3 py-2 bg-stone-900 text-white text-sm font-medium rounded-xl hover:bg-stone-800 transition-colors"
        >
          <Plus size={16} />
          New
        </button>
      </section>

      <section className="bg-white/60 p-4 rounded-xl border border-stone-100">
        <h3 className="text-xs font-bold text-stone-400 uppercase tracking-widest mb-3">Recent Sessions</h3>
        {notebooks.length === 0 ? (
          <p className="text-sm text-stone-400 italic">No notebooks yet. Create one to get started.</p>
        ) : (
          <div className="space-y-2">
            {notebooks.map((nb) => (
              <div
                key={nb.id}
                className={`group flex items-center justify-between p-3 rounded-lg cursor-pointer transition-all ${
                  activeNotebook === nb.id ? 'bg-stone-900 text-white' : 'bg-stone-50 hover:bg-stone-100'
                }`}
                onClick={() => onSelect(nb.id)}
              >
                <div className="flex-1 min-w-0">
                  <p className={`text-sm font-medium truncate ${activeNotebook === nb.id ? 'text-white' : 'text-stone-900'}`}>
                    {nb.name}
                  </p>
                  <p className={`text-xs ${activeNotebook === nb.id ? 'text-stone-300' : 'text-stone-400'}`}>
                    {nb.moleculeName} · {formatDate(nb.timestamp)}
                  </p>
                </div>
                <button
                  onClick={(e) => { e.stopPropagation(); onDelete(nb.id); }}
                  className={`p-1.5 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity ${
                    activeNotebook === nb.id ? 'hover:bg-stone-700 text-white' : 'hover:bg-red-100 text-red-600'
                  }`}
                >
                  <Trash2 size={14} />
                </button>
              </div>
            ))}
          </div>
        )}
      </section>

      <section className="p-4 bg-blue-50 border border-blue-100 rounded-xl">
        <h3 className="text-sm font-bold text-blue-800 mb-2">Using Notebooks</h3>
        <p className="text-xs text-blue-700 leading-relaxed">
          Notebooks save your analysis sessions including molecule data, analysis results, and notes. Each notebook is tied to a specific molecule.
        </p>
      </section>
    </div>
  );
};

const DatabaseSidebar: React.FC<{
  searchQuery: string;
  onSearchChange: (q: string) => void;
  onSearch: () => void;
  results: PubChemResult[];
  isSearching: boolean;
  onSelect: (result: PubChemResult) => void;
}> = ({ searchQuery, onSearchChange, onSearch, results, isSearching, onSelect }) => (
  <div className="space-y-6">
    <section>
      <h2 className="text-2xl font-bold text-stone-900">Molecule Database</h2>
      <p className="text-sm text-stone-500 mt-1">Search PubChem for chemical data</p>
    </section>

    <div className="relative">
      <input
        type="text"
        value={searchQuery}
        onChange={(e) => onSearchChange(e.target.value)}
        onKeyDown={(e) => e.key === 'Enter' && onSearch()}
        placeholder="Search molecules (e.g. Aspirin, Caffeine)..."
        className="w-full bg-white border border-stone-200 rounded-xl py-3 pl-4 pr-12 text-stone-800 placeholder:text-stone-400 focus:outline-none focus:ring-2 focus:ring-stone-900/10 focus:border-stone-400 transition-all"
      />
      <button
        onClick={onSearch}
        disabled={isSearching}
        className="absolute right-2 top-1/2 -translate-y-1/2 bg-stone-900 text-white p-2 rounded-lg hover:bg-stone-800 disabled:opacity-50 transition-colors"
      >
        {isSearching ? <Loader2 className="animate-spin" size={16} /> : <Search size={16} />}
      </button>
    </div>

    <section className="bg-white/60 p-4 rounded-xl border border-stone-100">
      <h3 className="text-xs font-bold text-stone-400 uppercase tracking-widest mb-3">
        {results.length > 0 ? `${results.length} Results` : 'Results'}
      </h3>
      {results.length === 0 && !isSearching ? (
        <p className="text-sm text-stone-400 italic">Search for a molecule to see results from PubChem.</p>
      ) : (
        <div className="space-y-2 max-h-64 overflow-y-auto">
          {results.map((result) => (
            <button
              key={result.cid}
              onClick={() => onSelect(result)}
              className="w-full p-3 bg-stone-50 hover:bg-stone-100 rounded-lg text-left transition-colors group"
            >
              <div className="flex items-start justify-between gap-2">
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-stone-900 group-hover:text-stone-700 truncate">{result.name}</p>
                  <p className="text-xs text-stone-500 font-mono">{result.formula}</p>
                </div>
                <ExternalLink size={14} className="text-stone-400 group-hover:text-stone-600 flex-shrink-0 mt-1" />
              </div>
              <p className="text-xs text-stone-400 mt-1">CID: {result.cid}</p>
            </button>
          ))}
        </div>
      )}
    </section>

    <section className="p-4 bg-green-50 border border-green-100 rounded-xl">
      <h3 className="text-sm font-bold text-green-800 mb-2">PubChem Integration</h3>
      <p className="text-xs text-green-700 leading-relaxed">
        Search millions of chemical compounds. Select a result to load it into the 3D Viewer or start a new notebook session.
      </p>
    </section>
  </div>
);

// ============================================================================
// MAIN APP
// ============================================================================

const App: React.FC = () => {
  // Core state
  const [activeTab, setActiveTab] = useState<TabId>('viewer');
  const [query, setQuery] = useState('');
  const [data, setData] = useState<MoleculeData | null>(null);
  const [status, setStatus] = useState<AppStatus>(AppStatus.IDLE);
  const [error, setError] = useState<string | null>(null);
  const [isRotating, setIsRotating] = useState(true);
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [isAnalysisMode, setIsAnalysisMode] = useState(false);
  const [apiConnected, setApiConnected] = useState(true);

  // Export dropdown
  const [exportOpen, setExportOpen] = useState(false);
  const exportRef = useRef<HTMLDivElement>(null);

  // Toast notifications
  const [toasts, setToasts] = useState<Toast[]>([]);

  // Notebooks
  const [notebooks, setNotebooks] = useState<NotebookEntry[]>([
    { id: 'nb1', name: 'Caffeine Analysis', timestamp: Date.now() - 86400000, moleculeName: 'Caffeine' },
    { id: 'nb2', name: 'Aspirin Study', timestamp: Date.now() - 172800000, moleculeName: 'Aspirin' },
  ]);
  const [activeNotebook, setActiveNotebook] = useState<string | null>(null);

  // Database search
  const [dbSearchQuery, setDbSearchQuery] = useState('');
  const [dbResults, setDbResults] = useState<PubChemResult[]>([]);
  const [isSearchingDb, setIsSearchingDb] = useState(false);

  // Add toast helper
  const addToast = useCallback((message: string, type: ToastType = 'info') => {
    const id = generateId();
    setToasts(prev => [...prev, { id, message, type }]);
  }, []);

  const dismissToast = useCallback((id: string) => {
    setToasts(prev => prev.filter(t => t.id !== id));
  }, []);

  // Handlers
  const handleSearch = useCallback(async (searchQuery: string) => {
    if (!searchQuery.trim()) return;

    setStatus(AppStatus.LOADING);
    setError(null);

    try {
      const result = await fetchMoleculeData(searchQuery);
      setData(result);
      setStatus(AppStatus.SUCCESS);
      setApiConnected(true);
      addToast(`Loaded: ${result.name}`, 'success');
    } catch (err) {
      console.error(err);
      setError(err instanceof Error ? err.message : 'Failed to generate molecule.');
      setStatus(AppStatus.ERROR);
      setApiConnected(false);
      addToast('Failed to load molecule', 'error');
    }
  }, [addToast]);

  const handleExport = useCallback((format: ExportFormat) => {
    if (!data) {
      addToast('No molecule loaded to export', 'error');
      return;
    }
    try {
      const content = exportMolecule(data, format);
      const filename = `${data.name.toLowerCase().replace(/\s+/g, '-')}${EXPORT_FORMATS.find(f => f.format === format)?.ext}`;
      const mimeType = format === 'json' ? 'application/json' : 'chemical/x-pdb';
      downloadFile(content, filename, mimeType);
      addToast(`Exported as ${format.toUpperCase()}`, 'success');
    } catch {
      addToast('Export failed', 'error');
    }
    setExportOpen(false);
  }, [data, addToast]);

  const handleDbSearch = useCallback(async () => {
    if (!dbSearchQuery.trim()) return;
    setIsSearchingDb(true);
    setDbResults([]);

    // Simulated PubChem search - in production, use actual PubChem API
    await new Promise(resolve => setTimeout(resolve, 800));

    const mockResults: PubChemResult[] = [
      { cid: 2519, name: dbSearchQuery + ' (Sample)', formula: 'C8H10N4O2' },
      { cid: 2964, name: 'Related Compound A', formula: 'C7H8N4O2' },
      { cid: 71274, name: 'Derivative Compound', formula: 'C9H12N4O2' },
    ].filter(r => r.name.toLowerCase().includes(dbSearchQuery.toLowerCase()) || dbSearchQuery.length > 2);

    if (mockResults.length === 0) {
      mockResults.push({ cid: 2519, name: dbSearchQuery, formula: 'C8H10N4O2' });
    }

    setDbResults(mockResults);
    setIsSearchingDb(false);
    addToast(`Found ${mockResults.length} results`, 'info');
  }, [dbSearchQuery, addToast]);

  const handleDbSelect = useCallback((result: PubChemResult) => {
    setActiveTab('viewer');
    handleSearch(result.name);
  }, [handleSearch]);

  const handleCreateNotebook = useCallback(() => {
    if (!data) {
      addToast('Load a molecule first', 'error');
      return;
    }
    const newNb: NotebookEntry = {
      id: generateId(),
      name: `${data.name} Notebook`,
      timestamp: Date.now(),
      moleculeName: data.name,
    };
    setNotebooks(prev => [newNb, ...prev]);
    setActiveNotebook(newNb.id);
    setActiveTab('notebooks');
    addToast('Notebook created', 'success');
  }, [data, addToast]);

  const handleDeleteNotebook = useCallback((id: string) => {
    setNotebooks(prev => prev.filter(nb => nb.id !== id));
    if (activeNotebook === id) setActiveNotebook(null);
    addToast('Notebook deleted', 'info');
  }, [activeNotebook, addToast]);

  const handleLaunchAnalysis = useCallback((moduleId: string) => {
    if (!data) {
      addToast('Load a molecule first', 'error');
      return;
    }
    setActiveTab('viewer');
    setIsAnalysisMode(true);
    addToast(`Launched ${ANALYSIS_MODULES.find(m => m.id === moduleId)?.name}`, 'success');
  }, [data, addToast]);

  // Effects
  useEffect(() => {
    handleSearch('Caffeine');
  }, [handleSearch]);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (exportRef.current && !exportRef.current.contains(e.target as Node)) {
        setExportOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [isDarkMode]);

  // Derived
  const tabs: { id: TabId; label: string; icon: React.ReactNode }[] = [
    { id: 'viewer', label: '3D Viewer', icon: <Eye size={18} /> },
    { id: 'analysis', label: 'Analysis', icon: <BarChart3 size={18} /> },
    { id: 'notebooks', label: 'Notebooks', icon: <FileText size={18} /> },
    { id: 'database', label: 'Molecule DB', icon: <Database size={18} /> },
  ];

  return (
    <div className={`relative w-full h-screen overflow-hidden flex flex-col transition-colors ${
      isDarkMode ? 'bg-stone-900' : 'bg-stone-50'
    }`}>
      {/* Background decoration */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-100 rounded-full blur-[120px] opacity-40 pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-red-100 rounded-full blur-[120px] opacity-40 pointer-events-none" />

      {/* Toast Container */}
      <div className="fixed top-20 right-4 z-50 space-y-2">
        {toasts.map(toast => (
          <ToastNotification key={toast.id} toast={toast} onDismiss={dismissToast} />
        ))}
      </div>

      {/* Header */}
      <header className={`relative z-10 px-6 py-4 flex items-center justify-between border-b backdrop-blur-md ${
        isDarkMode ? 'border-stone-700 bg-stone-900/50' : 'border-stone-200 bg-white/50'
      }`}>
        <div className="flex items-center gap-3">
          <div className="bg-stone-900 p-2 rounded-xl text-white">
            <Beaker size={24} />
          </div>
          <div>
            <h1 className={`text-xl font-bold tracking-tight ${isDarkMode ? 'text-white' : 'text-stone-900'}`}>
              Molecule Studio
            </h1>
            <p className="text-[10px] uppercase tracking-widest font-bold text-stone-400">GenAI Visualizer</p>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex items-center gap-2 px-4 py-1.5 bg-stone-100/50 rounded-2xl">
          {tabs.map(tab => (
            <TabButton
              key={tab.id}
              id={tab.id}
              label={tab.label}
              icon={tab.icon}
              active={activeTab === tab.id}
              onClick={() => setActiveTab(tab.id)}
            />
          ))}
        </div>

        {/* Right toolbar */}
        <div className="flex items-center gap-3">
          {/* DB Search (separate from main generator search) */}
          <div className="relative hidden lg:block">
            <input
              type="text"
              value={dbSearchQuery}
              onChange={(e) => setDbSearchQuery(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleDbSearch()}
              placeholder="Search PubChem..."
              className={`w-48 bg-white border border-stone-200 rounded-xl py-2 pl-4 pr-10 text-sm text-stone-800 placeholder:text-stone-400 focus:outline-none focus:ring-2 focus:ring-stone-900/10 focus:border-stone-400 transition-all`}
            />
            <button
              onClick={handleDbSearch}
              disabled={isSearchingDb}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-stone-400 hover:text-stone-900 transition-colors"
            >
              {isSearchingDb ? <Loader2 className="animate-spin" size={14} /> : <Search size={14} />}
            </button>
          </div>

          {/* Export Dropdown */}
          <div className="relative" ref={exportRef}>
            <button
              onClick={() => setExportOpen(!exportOpen)}
              className={`flex items-center gap-2 px-3 py-2 rounded-xl font-medium text-sm transition-all ${
                exportOpen
                  ? 'bg-stone-900 text-white'
                  : `border ${isDarkMode ? 'border-stone-600 text-stone-300 hover:text-white hover:border-stone-500' : 'border-stone-200 text-stone-600 hover:text-stone-900 hover:border-stone-400'}`
              }`}
            >
              <Download size={16} />
              Export
              <ChevronDown size={14} className={`transition-transform ${exportOpen ? 'rotate-180' : ''}`} />
            </button>
            {exportOpen && (
              <div className={`absolute right-0 mt-2 w-48 rounded-xl shadow-lg border overflow-hidden ${
                isDarkMode ? 'bg-stone-800 border-stone-600' : 'bg-white border-stone-200'
              }`}>
                {EXPORT_FORMATS.map(({ format, label }) => (
                  <button
                    key={format}
                    onClick={() => handleExport(format)}
                    className={`w-full px-4 py-2.5 text-sm text-left flex items-center gap-2 hover:bg-stone-100 transition-colors ${
                      isDarkMode ? 'text-stone-200 hover:bg-stone-700' : 'text-stone-700'
                    }`}
                  >
                    <Table2 size={14} />
                    {label}
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Analysis Mode Toggle */}
          <button
            onClick={() => setIsAnalysisMode(!isAnalysisMode)}
            className={`p-2 rounded-xl border transition-all ${isAnalysisMode ? 'bg-amber-500 text-white border-amber-500' : isDarkMode ? 'border-stone-600 text-stone-300 hover:text-white' : 'border-stone-200 text-stone-600 hover:text-stone-900'}`}
            title="Analysis Mode"
          >
            <FlaskConical size={20} />
          </button>

          {/* Dark Mode Toggle */}
          <button
            onClick={() => setIsDarkMode(!isDarkMode)}
            className={`p-2 rounded-xl border transition-all ${isDarkMode ? 'border-stone-600 text-yellow-400 hover:text-yellow-300' : 'border-stone-200 text-stone-600 hover:text-stone-900'}`}
            title="Dark Mode"
          >
            {isDarkMode ? <Sun size={20} /> : <Moon size={20} />}
          </button>

          <div className={`h-6 w-px ${isDarkMode ? 'bg-stone-700' : 'bg-stone-200'}`} />

          <ConnectionStatus connected={apiConnected} />

          <a href="https://github.com" target="_blank" className={`${isDarkMode ? 'text-stone-400 hover:text-white' : 'text-stone-400 hover:text-stone-900'} transition-colors`}>
            <Github size={20} />
          </a>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 relative flex">
        {/* Left Sidebar */}
        <aside className={`relative z-10 w-80 p-6 overflow-y-auto backdrop-blur-sm border-r ${
          isDarkMode ? 'border-stone-700 bg-stone-900/30' : 'border-stone-100 bg-white/40'
        }`}>
          {activeTab === 'viewer' && (
            <ViewerSidebar data={data} status={status} error={error} onSearch={handleSearch} />
          )}
          {activeTab === 'analysis' && (
            <AnalysisSidebar onLaunch={handleLaunchAnalysis} />
          )}
          {activeTab === 'notebooks' && (
            <NotebooksSidebar
              notebooks={notebooks}
              activeNotebook={activeNotebook}
              onSelect={setActiveNotebook}
              onCreate={handleCreateNotebook}
              onDelete={handleDeleteNotebook}
            />
          )}
          {activeTab === 'database' && (
            <DatabaseSidebar
              searchQuery={dbSearchQuery}
              onSearchChange={setDbSearchQuery}
              onSearch={handleDbSearch}
              results={dbResults}
              isSearching={isSearchingDb}
              onSelect={handleDbSelect}
            />
          )}
        </aside>

        {/* Right Content */}
        <section className={`flex-1 relative ${isDarkMode ? 'bg-stone-800/30' : 'bg-stone-100/30'}`}>
          {/* Watermark */}
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none opacity-[0.03] select-none">
            <h1 className={`text-[20vw] font-black uppercase ${isDarkMode ? 'text-white' : 'text-stone-900'}`}>LAB</h1>
          </div>

          {/* Analysis Mode Banner */}
          {isAnalysisMode && data && (
            <div className="absolute top-4 left-1/2 -translate-x-1/2 z-20 px-6 py-2 bg-amber-500 text-white font-bold text-sm rounded-full shadow-lg flex items-center gap-2">
              <FlaskConical size={16} />
              Analysis Mode Active — {ANALYSIS_MODULES[0]?.name || 'Module'}
            </div>
          )}

          {/* Loading overlay */}
          {status === AppStatus.LOADING && (
            <div className={`absolute inset-0 z-20 backdrop-blur-sm flex flex-col items-center justify-center gap-4 ${
              isDarkMode ? 'bg-stone-900/50' : 'bg-stone-50/50'
            }`}>
              <div className="relative">
                <div className="w-16 h-16 border-4 border-stone-200 border-t-stone-900 rounded-full animate-spin" />
                <div className="absolute inset-0 flex items-center justify-center">
                  <Beaker className="text-stone-900" size={24} />
                </div>
              </div>
              <div className="text-center">
                <p className="font-bold text-stone-900">Synthesizing structure...</p>
                <p className="text-xs text-stone-400">Gemini is calculating atomic coordinates</p>
              </div>
            </div>
          )}

          {/* 3D Canvas */}
          <div className="w-full h-full cursor-grab active:cursor-grabbing">
            <MoleculeCanvas data={data} isRotating={isRotating} />
          </div>

          {/* Controls hint */}
          <div className="absolute bottom-8 right-8 flex gap-4">
            <div className={`flex items-center gap-4 backdrop-blur px-4 py-2 rounded-2xl shadow-sm border text-[10px] font-bold uppercase tracking-widest ${
              isDarkMode ? 'bg-stone-800/80 border-stone-600 text-stone-300' : 'bg-white/80 border-stone-200 text-stone-400'
            }`}>
              <div className="flex items-center gap-1">
                <div className={`w-4 h-4 rounded ${isDarkMode ? 'bg-stone-700 border-stone-500' : 'bg-stone-100 border-stone-300'}`} /> Orbit
              </div>
              <div className="flex items-center gap-1">
                <div className={`w-4 h-4 rounded ${isDarkMode ? 'bg-stone-700 border-stone-500' : 'bg-stone-100 border-stone-300'}`} /> Zoom
              </div>
            </div>

            {/* Auto-rotate toggle */}
            <button
              onClick={() => setIsRotating(!isRotating)}
              className={`p-2 rounded-xl border shadow-sm transition-all ${
                isRotating
                  ? 'bg-stone-900 text-white border-stone-900'
                  : isDarkMode ? 'bg-stone-800 text-stone-300 border-stone-600' : 'bg-white text-stone-600 border-stone-200'
              }`}
              title="Toggle Auto-rotation"
            >
              <RotateCw size={18} className={isRotating ? 'animate-spin-slow' : ''} />
            </button>
          </div>
        </section>
      </main>

      {/* Notebook Content Area (when notebook is active) */}
      {activeTab === 'notebooks' && activeNotebook && (
        <div className={`absolute inset-0 z-30 flex items-center justify-center ${
          isDarkMode ? 'bg-stone-900/90' : 'bg-white/90'
        }`}>
          <div className={`max-w-lg p-8 rounded-2xl border text-center ${isDarkMode ? 'bg-stone-800 border-stone-700' : 'bg-white border-stone-200'}`}>
            <FileText size={48} className={`mx-auto mb-4 ${isDarkMode ? 'text-stone-400' : 'text-stone-300'}`} />
            <h2 className={`text-xl font-bold mb-2 ${isDarkMode ? 'text-white' : 'text-stone-900'}`}>
              {notebooks.find(nb => nb.id === activeNotebook)?.name}
            </h2>
            <p className={`text-sm ${isDarkMode ? 'text-stone-400' : 'text-stone-500'}`}>
              Notebook content would appear here. Analysis results, notes, and visualizations are stored in each notebook session.
            </p>
            <button
              onClick={() => setActiveNotebook(null)}
              className="mt-4 px-4 py-2 bg-stone-900 text-white text-sm font-medium rounded-xl hover:bg-stone-800 transition-colors"
            >
              Close Notebook
            </button>
          </div>
        </div>
      )}

      <style>{`
        @keyframes spin-slow {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        .animate-spin-slow {
          animation: spin-slow 8s linear infinite;
        }
        @keyframes slide-in {
          from { transform: translateX(100%); opacity: 0; }
          to { transform: translateX(0); opacity: 1; }
        }
        .animate-slide-in {
          animation: slide-in 0.3s ease-out;
        }
      `}</style>
    </div>
  );
};

export default App;
