// Export molecule data to various formats

export interface MoleculeData {
  name: string;
  formula: string;
  description: string;
  category: string;
  atoms: { element: string; x: number; y: number; z: number }[];
  bonds: number[][];
}

export function exportToPDB(molecule: MoleculeData): string {
  const lines: string[] = [];
  lines.push("HEADER    " + molecule.name.toUpperCase().substring(0, 40).padEnd(40));
  lines.push("TITLE     " + molecule.name);
  lines.push("AUTHOR    Molecule Studio Scientific Platform");

  molecule.atoms.forEach((atom, i) => {
    const idx = i + 1;
    const x = atom.x.toFixed(3).padStart(8);
    const y = atom.y.toFixed(3).padStart(8);
    const z = atom.z.toFixed(3).padStart(8);
    lines.push(
      `ATOM  ${idx.toString().padStart(5)}  ${atom.element.padEnd(2)}${"CA".padStart(3)} ${"LIG".padStart(3)}  ${idx.toString().padStart(4)}    ${x}${y}${z}  1.00  0.00          ${atom.element.padEnd(2)}`
    );
  });

  molecule.bonds.forEach((bond, i) => {
    lines.push(`BOND ${(i + 1).toString().padStart(5)} ${(bond[0] + 1).toString().padStart(5)} ${(bond[1] + 1).toString().padStart(5)}`);
  });

  lines.push("END");
  return lines.join("\n");
}

export function exportToXYZ(molecule: MoleculeData): string {
  const lines: string[] = [];
  lines.push(molecule.atoms.length.toString());
  lines.push(molecule.name + " - Generated by Molecule Studio");
  molecule.atoms.forEach(atom => {
    lines.push(`${atom.element} ${atom.x.toFixed(6)} ${atom.y.toFixed(6)} ${atom.z.toFixed(6)}`);
  });
  return lines.join("\n");
}

export function exportToMOL(molecule: MoleculeData): string {
  const lines: string[] = [];
  lines.push(molecule.name + " - Molecule Studio");
  lines.push("  -Molecule Studio-  v2000");

  const nAtoms = molecule.atoms.length;
  const nBonds = molecule.bonds.length;
  lines.push(`${nAtoms.toString().padStart(3)}${nBonds.toString().padStart(3)}  0  0  0  0  0  0  0  0  1 V2000`);

  molecule.atoms.forEach(atom => {
    lines.push(
      `${(atom.x * 1.5).toFixed(4).padStart(10)}${(atom.y * 1.5).toFixed(4).padStart(10)}${(atom.z * 1.5).toFixed(4).padStart(10)} ${atom.element.padEnd(3)} 0  0  0  0  0  0  0  0  0  0  0  0`
    );
  });

  molecule.bonds.forEach(bond => {
    lines.push(`${(bond[0] + 1).toString().padStart(3)}${(bond[1] + 1).toString().padStart(3)}  1  0  0  0  0`);
  });

  lines.push("M  END");
  return lines.join("\n");
}

export function exportToJSON(molecule: MoleculeData): string {
  return JSON.stringify(molecule, null, 2);
}

export function downloadFile(content: string, filename: string, mimeType: string = "text/plain"): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
